wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Images_wandb_delimeter_predictions:
        key: Images_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': negative
          '1': person
          '2': car
          '3': van
          '4': truck
          '5': bus
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1644492894
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 13
      - 16
      4: 3.9.6
      5: 0.12.10
      8:
      - 5
adam:
  desc: null
  value: false
batch_size:
  desc: null
  value: 16
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: true
cfg:
  desc: null
  value: ./models/custom_yolov5l.yaml
data:
  desc: null
  value: /home/omni/Train_YOLOv5/yolov5/yolov5-dataset-2-1/data.yaml
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 400
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 416
  - 416
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
log_artifacts:
  desc: null
  value: false
log_imgs:
  desc: null
  value: 16
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: yolov5s_results
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/yolov5s_results
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 16
weights:
  desc: null
  value: ''
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
